[Issue-81] Gracefully handle missing dependencies. (#82)
* [ISSUE-81] catch NoClassDefFoundError errors and bubble up appropriately

* [ISSUE-81] Update changelog

* Add missing changelog entries

* [ISSUE-81] Add more helpful exception error msg